---
apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod2
  annotations:
    buildversion: 1.10
  labels:
    app: newapp
spec:
  containers:
  - name: nginx-container
    image: nginx
  nodename: worker
...