---
apiVersion: v1
kind: Service
metadata:
  name: myapp-service2
spec:
  selector: 
      app: myapp
      type: front-end
  type: LoadBalancer
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30008
...
