---
apiVersion: v1
kind: Pod
metadata:
  name: myapp-prod8
spec:
  containers:
  - name: data-processor
    image: nginx
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: size
            operator: In
            values:
            - large
            - medium
...
