#!/usr/bin/expect -f

spawn ssh-copy-id root@master
expect "password:"
send "redhat\n"
expect eof

spawn ssh-copy-id root@worker1
expect "password:"
send "redhat\n"
expect eof

spawn ssh-copy-id root@worker2
expect "password:"
send "redhat\n"
expect eof
