---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  namespace: dev
  labels:
    app: myapp
    type: front-end
spec:
  replicas: 2
  selector:
    matchLabels:
      type: front-end
  template:
     metadata:
       name: myapp-pod
       labels:
         app: myapp
         type: front-end
     spec:
       containers:
         - name: nginx-container
           image: nginx
           resources:
             limits:
               cpu: "2"
               memory: 20Mi
             requests:
               cpu: "0.2"
               memory: 15Mi
...
